config/routes.rb
Cinema::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :movies do
    resources :reviews
  end
  
  resources :users do
    resources :reviews
  end
  
  root to: 'movies#index'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :description, :image, :name, :average_rating
  has_many :reviews
  
  validates :description, :presence => true
  validates :image, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
  attr_accessible :content, :name, :rating, :user_id, :movie_id
  
  validates :user_id, :presence => true
  validates :rating, :presence => true
  validates :content, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
  attr_protected :provider, :uid, :oauth_token, :oauth_expires_at, :created_at,
    :updated_at 
  has_many :reviews
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @search = Movie.search(params[:q])
    @movies = @search.result
  end

  def show
    @movie = Movie.find(params[:id])
    
    if session[:user_id] 
	  @user = User.find(session[:user_id])
	else 
	  @user = User.new(:name => "Not Logged In")
	end
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    if session[:user_id]
      @movie = Movie.find(params[:movie_id])
      @review = @movie.reviews.create!(params[:review])
      average = Review.average(:rating, :conditions => ['movie_id = ?', params[:movie_id]])
      Movie.update(params[:movie_id], :average_rating => average)
      redirect_to @review.movie, notice: "Review has been created."
    else
      redirect_to :back, notice: "Please Log in"
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
	
  def movies
    @user = Movie.find(params[:id])
  end
  
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    
    respond_to do |format|
      if session[:user_id] == @user.id
    	session[:user_id] = nil
        @user.destroy
        format.html { redirect_to :action => 'index', notice: "account destroyed" }
        format.json { head :no_content }
        
      else
        format.html {redirect_to :back, notice: "You may only destroy your own account"}
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoovieReview</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if current_user %>
          Signed in as <strong><%= current_user.name %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out" %>
          <%= link_to "Profile", "/users/" + session[:user_id].to_s(), id: "profile" %>
        <% else %>
          <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_movie.html.erb
<div class="movie">
  <%= image_tag movie.image %>
  <h2><%= movie.name %></h2>
  <p><%= movie.description %></p>
  <% if current_page? movie %>
    <p><%= link_to "Back to Movies", movies_path %></p>
  <% else %>
    <p><%= link_to "Read Reviews", movie %></p>
  <% end %>
  <div class="clear"></div>
</div>

app/views/movies/index.html.erb
<h1>Movies</h1>

<%= search_form_for @search do |f| %>
  
  <div class="field">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

<table id="movies">
  <tr>
    <th><%= sort_link @search, :name, "Movie" %></th>
    <th><%= sort_link @search, :updated_at, "Updated at" %></th>
    <th><%= sort_link @search, :average_rating, "Rating" %></th>
  </tr>
</table>


<%= render @movies %>

app/views/movies/show.html.erb
<div id="movie">
  <%= render @movie %>
</div>

<p>
  <b>Title:</b>
  <%=h @user.name %>
</p>

<div id="reviews">
  <h2><%= pluralize @movie.reviews.size, "Review" %></h2>

  <% @movie.reviews.each do |review| %>
    <div class="review">
      <div class="content"><%= review.content %></div>
      <em>
        &mdash;
        <%= review.name %> gave it
        <strong><%= pluralize review.rating, "star" %></strong>
      </em>
    </div>
  <% end %>

  <h3>Write a review</h3>
  <%= form_for [@movie, Review.new] do |f| %>
    <div class="field">
      <%= f.label :rating %>
      <%= f.select :rating, 1..5 %>
    </div>
    <div class="field">
      <%= f.label :name, @user.name %>
      <%= f.hidden_field :user_id, :value => @user.id %>
    </div>
    <div class="field">
      <%= f.text_area :content, rows: 5, cols: 40 %>
    </div>
    <div class="actions"><%= f.submit %></div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Show</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Show:</b>
  <%= @user.name %>
</p>

<div id="reviews">
  <h2><%= pluralize @user.reviews.size, "Review" %></h2>

  <% @user.reviews.each do |review| %>
    <div class="review">
      <div class="movietitle"> <%= Movie.find(review.movie_id).name %> </div>
      <div class="content"><%= review.content %></div>
      <em>
        &mdash;
        <%= @user.name %> gave it
        <strong><%= pluralize review.rating, "star" %></strong>
      </em>
    </div>
  <% end %>
</div>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>